spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=example;encrypt=true;trustServerCertificate=true;
    username: sa
    password: P@ssw0rd!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jackson:
    default-property-inclusion: always

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

mybatis:
  mapper-locations: classpath:/db/mapper/**/*.xml

logging:
  level:
    org.springframework.web: debug
    com.asc.infrastructure.db.mapper: debug
